### ISSUE TITLE
CI should run automatically for non-public PR to develop branch

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-data#83]
When I create a PR to the "develop" branch the CI unit tests are skipped and I have to set the `approve-for-ci` label to start them. "develop" should behave like "main" and the tests should be automatically run for non-public PRs.

**Comment by dtip** [comment]
@sandorkertesz our definition of a "public PR" is currently "a PR which is opened from a fork". All public PRs need to use the labels to run CI. The CI will run automatically for any PR opened from a branch within ecmwf/earthkit-data e.g. this one from James: https://github.com/ecmwf/earthkit-data/pull/105

This PR from Eddy came from a fork, which is why it was given the "contributor" label and so needs the "approved-for-ci" label for the CI to run: https://github.com/ecmwf/earthkit-data/pull/76

**Comment by sandorkertesz** [comment]
@dtip, it still does not work for me. I still need to add/remove the  `approve-for-ci` label when I create a PR into develop from a non-fork branch. Otherwise the tests are not run. See: #106.

**Comment by dtip** [comment]
Fixed by https://github.com/ecmwf/earthkit-data/commit/b2ce68209b8edbad022321ea92e24492e15f614b
